apiVersion: v1
kind: Secret
metadata:
  name: metabase-secret
type: Opaque
data:
  # Base64-encoded values
  DB_NAME: <BASE64_ENCODED_DB_NAME>
  DB_PORT: <BASE64_ENCODED_DB_PORT>
  DB_USER: <BASE64_ENCODED_DB_USER>
  DB_PASS: <BASE64_ENCODED_DB_PASSWORD>