apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: iwalucas/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: DB_NAME
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: DB_PASS
            - name: MB_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: DB_HOST