apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world
spec:
  parentRefs:
  - name: internal-gateway
    sectionName: http
  # hostnames: 
  # - "testing.com" if you want to domain
  rules:
  - matches:
    - path:
        type: Exact
        value: /
    backendRefs:
    - name: hello-world
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-testing-services
spec:
  to:
  - group: ""
    kind: Service
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: default
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: hello-world-prefix
# spec:
#   parentRefs:
#   - name: internal-gateway
#     sectionName: http
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /test-other
#     backendRefs:
#     - name: hello-world
#       port: 80